os:
- linux
sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libstdc++6
            - fonts-droid
git:
  depth: 3
env:
  - FLUTTER_VERSION=beta
  - FLUTTER_VERSION=dev
cache:
  directories:
    - $HOME/.pub-cache
matrix:
  allow_failures:
    - env: FLUTTER_VERSION=dev
before_script:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
